version: '3.8'

services:
  quiz-app:
    build: .
    image: quiz-app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
    ports:
      - '3000:3000'
    depends_on:
      - postgresdb
    volumes:
      - .:/usr/src/quiz-app
    networks:
      - node-network

  postgresdb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - node-network

volumes:
  dbdata:
    driver: local

networks:
  node-network:
    driver: bridge
